### PR TITLE
Fixes #14 Remove viewcount

### LINKED ISSUE #14: Remove View count.
View Count of a video should not be visible in the queue. When a video is loaded from the playlists, its view count should not be displayed because view count is stored as a static value in the playlist whereas views of a video keep on increasing.

### PR DESCRIPTION
**Pull request by Tlazypanda**

### CODE REVIEW

**Comment by adeora7** [comment]
This will prevent t view count from being displayed but can you also make the change so that we don't store the view count of new videos being added anymore. It can be found in background.js file.

**Comment by Tlazypanda** [comment]
Updated @adeora7

**Comment by Tlazypanda** [comment]
@adeora7 is this alright?

**Comment by adeora7** [comment]
Yeah, looks good to me !!

**Pull request merged**
