### PR TITLE
Fixes #16 Adding contributors Fixes #15 Add screenshots

### LINKED ISSUE #15: Add screenshots.
Add 2 or 2 screenshots from the chrome extension to the readme file. The screenshots should show different features of the extension.

### LINKED ISSUE #16: Add contributors section.
Add a contributors section to the readme file. Preferably in the end.  Refer [this](https://github.com/adeora7/hacktoberfest_progress/).

### PR DESCRIPTION
**Pull request by Tlazypanda**
I have just looked up the previous issues and added the contributors for now.Is there anyone else that I need to include? 
image

### CODE REVIEW

**Comment by adeora7** [comment]
Yes, please add you name if possible. Also, if possible then add tags #documentation in front of your and kaustubh's name

**Comment by Tlazypanda** [comment]
Ok sir! on it.Also sir I am unable to download the extension from the chromestore because it is forbidden(don't have permission to download) So I have included the same screenshots from the extension page.

**Comment by Tlazypanda** [comment]
This is the final preview
image
image

**Comment by adeora7** [comment]
@Tlazypanda  Strange. It should not be forbidden. There isn't any such issue reported by the users.

**Pull request merged**
