### PR TITLE
Change video to embed

### PR DESCRIPTION
**Pull request by Booom3**
This lets the user fullscreen the video by pressing F11 which will
retain fullscreen through changing the page

Oh and it also fixes a bug with right click add to queue videos without "/watch?v=" in the URL, like such:
https://www.youtube.com/embed/UkWd0azv3fQ?autoplay=1

### CODE REVIEW

**Comment by adeora7** [comment]
Hey, sorry I didn't see the PR. I will verify now.

**Comment by adeora7** [comment]
@Booom3 By changing to embed the suggestion which come on youtube will no longer be visible while video is playing. How will a person add more videos to the queue. He/she will have to go to another youtube tab to do so. Generally we add the videos related to the one which we are playing. So I don't think this is the solution. Also I didn't get which bug you are referencing here. Can you add an issue reference link for the same.

I tried to work on this issue but then starting working on something else. This is what can be done. you can create a variable in the local storage for full screen mode. The user can either have an option for that in the popup(strongly preferred) or you can map it to the youtube player full screen button. So whenever a new video plays, we check the local varibale for full screen mode and perform a click through in-page javascript on the youtube video player full screen button.

**Comment by Booom3** [comment]
This is true, I just personally don't use that. But you could just implement an option to toggle between the modes, to go embed link or regular link.

Your suggestion does not work as the browser will reject programmatic attempts to fullscreen the video. It keeps track of where events come from and if it tries to fullscreen the video through a click generated by the code it will fail.

**Comment by adeora7** [comment]
@Booom3  I tried from the console and it works. I am not sure about the injected script. I will check and let you know.

**Pull request closed without merging**
